#!/usr/bin/env bash

set -eu -o pipefail

DICT=$XDG_DATA_HOME/dict.json

menu() {
  fzfmenu --ansi --highlight-line --read0 --wrap --wrap-sign " ↳ " "$@"
}

topic="$(jq --raw-output0 \
  'group_by(.topic) | map({topic: (.[0] | .topic), count: length}) | sort_by(-.count) | map(.topic) | [""] + . | .[]' \
  "$DICT" \
  | menu --prompt "dict topic> ")"

if [ -z "$topic" ]; then
  selection="$(jq --raw-output0 \
    'map(.text) | .[]' \
    "$DICT" \
    | menu --prompt "dict text> ")"
else
  selection="$(jq --raw-output0 --arg 'topic' "$topic" \
    'map(select(.topic == $topic)) | map(.text) | .[]' \
    "$DICT" \
    | menu --prompt "dict text> ")"
fi

for selection_type in clipboard primary; do
  echo -n "$selection" | xsel --logfile /dev/null -i --"$selection_type"
done
