#!/usr/bin/env sh

# A tiny wrapper on top of `fzfmenu` that is compatible with `clipmenu`.
#
# The `fzfmenu` cannot be used with `clipmenu` directly, because `clipmenu`
# doesn't recognize it as `fzf` compatible, but as `dmenu` compatible. Thus,
# passes to it these extra options: `-l "${CM_HISTLENGTH}"`. The options are
# __not supported__ by `fzf`.
#
# This script can be used with `clipmenu` like this:
#
# `CM_LAUNCHER=fzfclipmenu clipmenu`

# Remove `launcher_args=(-l "${CM_HISTLENGTH}")`.
shift 2
fzfmenu "$@"
