#!/usr/bin/env bash

shopt -s nullglob globstar

if [[ -n $WAYLAND_DISPLAY ]]; then
  dmenu=dmenu-wl
elif [[ -n $DISPLAY ]]; then
  dmenu=dmenu
else
  echo "Error: No Wayland or X11 display detected" >&2
  exit 1
fi

profile=$(pfile ls | "$dmenu" -p 'Chose profile:' "$@")

[[ -n $profile ]] || exit

pfile switch "$profile" 2> /dev/null
