#!/usr/bin/env bash

set -eu

disk="$(find /mnt/ -mindepth 1 -maxdepth 1 -type d | fzf --prompt 'Pick a disk> ' | tr -s ' ')"

paths=(
  '.ssh'
  '.local/share/dict.txt'
  '.local/share/gnupg'
  '.local/share/pfile'
  'documents'
  'notes'
  'projects'
  'science'
  'tools'
)
common_options=(
  '-aRv'
  '--update'
  '--delete'
  '--exclude' '.mypy_cache'
  '--exclude' '.venv'
  '--exclude' 'venv'
  '--exclude' '__pycache__'
  '--exclude' '.stack-work'
)

mkdir -p "$disk/sync"

for path in "${paths[@]}"; do
  rsync "${common_options[@]}" "$HOME/$path" "$disk/sync"
done
