#!/usr/bin/env bash

set -eu

main() {
  if [ "$#" -eq 0 ]; then
    help
    exit
  fi

  local dest=''
  local common_options=()

  while [ "$#" -gt 0 ]; do
    case "$1" in
      '-h' | '--help')
        help
        exit
        ;;
      '-u' | '--update')
        common_options+=('--update')
        shift
        ;;
      '--')
        if ! [ "$#" -eq 2 ]; then
          echo 'Expected exactly single DEST' >&2
          exit 1
        fi
        dest="$2"
        break
        ;;
      *)
        if ! [ "$#" -eq 1 ]; then
          echo 'Expected exactly single DEST' >&2
          exit 1
        fi
        dest="$1"
        break
        ;;
    esac
  done

  if [ -z "$dest" ]; then
    echo 'DEST argument is required.' >&2
    exit 1
  fi

  local local_profile
  local_profile=$(basename "$(realpath -e "$XDG_DATA_HOME/pfile/current")")

  local remote_profile
  remote_profile=$(basename "$(ssh "${dest%%:*}" realpath -e .local/share/pfile/current)")

  if ! [ "$local_profile" = "$remote_profile" ]; then
    echo -n 'Refuse to sync because local profile ('"$local_profile"')' >&2
    echo -n ' doesn'\''t match remote profile ('"$remote_profile"').' >&2
    echo >&2
    exit 1
  fi

  local paths
  paths=(
    '.ssh'
    '.local/share/dict.txt'
    '.local/share/gnupg'
    '.local/share/pfile'
    'documents'
    'notes'
    'projects'
    'science'
    'tools'
  )
  common_options+=(
    '-aRv'
    '--info=progress2'
    '--mkpath'
    '--omit-dir-times'
    '--delete'
    '--exclude' '.mypy_cache'
    '--exclude' '.venv'
    '--exclude' 'venv'
    '--exclude' '__pycache__'
    '--exclude' '.stack-work'
  )

  for path in "${paths[@]}"; do
    rsync "${common_options[@]}" "$HOME/$path" "$dest"
  done

  exit 0
}

help() {
  cat >&2 << 'EOF'
sync-push - copy predefined directories to DEST

Usage: sync-push [-h|--help] DEST

  Copy predefined directories to DEST with `rsync`.

Available options:
  -h,--help                Show this help text
  -u,--update              Pass `--update` to `rsync`
EOF
}

main "$@"
