#!/usr/bin/env sh

set -eu

WALLPAPERS_DIR="$XDG_DATA_HOME/wallpapers/"

main() {
  if [ "$#" -eq 0 ]; then
    help
    exit
  fi

  case "$1" in
    '-l' | '--load')
      set_wallpaper "$WALLPAPERS_DIR/current"
      ;;
    '-p' | '--pick')
      pick
      ;;
    '-r' | '--random')
      random
      ;;
    '-h' | '--help')
      help
      ;;
  esac
}

pick() {
  wallpapers="$(get_available_wallpapers)"
  if [ -z "$wallpapers" ]; then
    exit 1
  fi

  chosen_wallpaper="$(echo "$wallpapers" | nsxiv -ito | head -1)"
  if [ -z "$chosen_wallpaper" ]; then
    exit 1
  fi

  set_current_wallpaper "$chosen_wallpaper"
}

random() {
  wallpapers="$(get_available_wallpapers | grep -vx "$(get_current_wallpaper)")"
  if [ -z "$wallpapers" ]; then
    exit 1
  fi

  chosen_wallpaper="$(echo "$wallpapers" | shuf -n 1)"
  set_current_wallpaper "$chosen_wallpaper"
}

get_available_wallpapers() {
  if ! [ -d "$WALLPAPERS_DIR" ]; then
    echo "$WALLPAPERS_DIR is not a directory." >&2
    exit 1
  fi

  find -L "$WALLPAPERS_DIR" -type f -iregex '.*\.\(png\|jpg\|jpeg\)'
}

set_current_wallpaper() {
  set_wallpaper "$1"
  ln -sf "$1" "$WALLPAPERS_DIR/current"
}

set_wallpaper() {
  feh --no-fehbg --bg-scale "$1"
}

get_current_wallpaper() {
  readlink -e "$WALLPAPERS_DIR/current"
}

help() {
  cat >&2 << 'EOF'
Usage: wallpaper [OPTIONS]

Options:
  -l, --load    Set most recent wallpaper $XDG_DATA_HOME/wallpapers/current.
  -p, --pick    Pick wallpaper from $XDG_DATA_HOME/wallpapers/.
  -r, --random  Set random wallpaper.
  -h, --help    Show this message and exit.
EOF
}

main "$@"
